services:
    # image project
    app-laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.3-fpm
        container_name: app-laravel
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/custom.ini:/etc/php/custom.ini
        ports:
            - "9000:9000"
        networks:
            - laravel-base

    # nginx
    nginx-laravel:
        image: nginx:alpine
        container_name: nginx-laravel
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel-base

    # db postgres
    db-laravel:
        platform: linux/x86_64
        image: mariadb
        container_name: db-laravel
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: db
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel-base

    # phpmyadmin
    phpmyadmin-laravel:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        container_name: phpmyadmin_laravel
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8081:80
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - /sessions
            - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            - ./docker/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
        networks:
            - laravel-base

networks:
    laravel-base:
        driver: bridge
